"""create message_vectorization table with vector index

Revision ID: 1e0bdc867412
Revises: 
Create Date: 2025-05-14 14:22:41.865255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '1e0bdc867412'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Activate the pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    # Create the message_vectorization table
    op.create_table('message_vectorization',
    sa.Column('id_message', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('embedding_message', Vector(768), nullable=False),
    sa.Column('date_vectorization', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_message')
    )
    op.create_index(op.f('ix_message_vectorization_id_message'), 'message_vectorization', ['id_message'], unique=False)
    op.create_index(op.f('ix_message_vectorization_message'), 'message_vectorization', ['message'], unique=False)
    op.drop_table('testeg')

    # create the index on the embedding column
    op.execute(
        """CREATE INDEX IF NOT EXISTS idx_vector_embedding_message
        ON message_vectorization
        USING ivfflat (embedding_message vector_cosine_ops)
        WITH (lists = 100);
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_vector_embedding_message")
    
    op.create_table('testeg',
    sa.Column('id', sa.CHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('embedding', Vector(768), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='documents_pkeyeg')
    )
    op.drop_index(op.f('ix_message_vectorization_message'), table_name='message_vectorization')
    op.drop_index(op.f('ix_message_vectorization_id_message'), table_name='message_vectorization')
    op.drop_table('message_vectorization')
    # ### end Alembic commands ###
