"""RemoveIndex

Revision ID: 585223542614
Revises: f507b37ef898
Create Date: 2025-05-15 16:08:26.286087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585223542614'
down_revision: Union[str, None] = 'f507b37ef898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_vectorization_message', table_name='message_vectorization')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_message_vectorization_message', 'message_vectorization', ['message'], unique=False)
    # ### end Alembic commands ###
