"""Initial migration and create table message_vectorization

Revision ID: befd18a93053
Revises: 
Create Date: 2025-05-07 16:17:51.370541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'befd18a93053'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_vectorization',
    sa.Column('id_message', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('embedding_message', sa.String(), nullable=False),
    sa.Column('date_vectorization', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_message')
    )
    op.create_index(op.f('ix_message_vectorization_embedding_message'), 'message_vectorization', ['embedding_message'], unique=False)
    op.create_index(op.f('ix_message_vectorization_id_message'), 'message_vectorization', ['id_message'], unique=False)
    op.create_index(op.f('ix_message_vectorization_message'), 'message_vectorization', ['message'], unique=False)
  
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_vectorization_message'), table_name='message_vectorization')
    op.drop_index(op.f('ix_message_vectorization_id_message'), table_name='message_vectorization')
    op.drop_index(op.f('ix_message_vectorization_embedding_message'), table_name='message_vectorization')
    op.drop_table('message_vectorization')
    # ### end Alembic commands ###
